name: Tests

on:
  workflow_run:
    workflows: [ "Codesniffer" ]
    types:
        - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --ignore-platform-reqs

      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install libmemcached-dev memcached zlib1g-dev
      - name: Start memcached daemons
        run: memcached -d -p 11211

      - name: Run tests
        run: phpunit